const demo=[
{id:1,name:'طقم قدور كوزينة 10 قطع',cat:'الكوزينة',price:899,old:1499,disc:40,img:'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80'},
{id:2,name:'خلاط كوزينة عالي الجودة',cat:'لافابو',price:420,old:650,disc:35,img:'https://images.unsplash.com/photo-1608198093002-ad4e005484ec?auto=format&fit=crop&w=800&q=80'},
{id:3,name:'سخان الماء 50 لتر',cat:'الشوفو',price:2249,old:2999,disc:25,img:'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80'},
{id:4,name:'إضاءة LED سقف',cat:'الضو',price:62,old:89,disc:30,img:'https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?auto=format&fit=crop&w=800&q=80'},
{id:5,name:'موقد غاز 4 عيون',cat:'الغاز',price:1199,old:1499,disc:20,img:'https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=800&q=80'},
{id:6,name:'طقم حمام عصري',cat:'الحمامات',price:1749,old:2499,disc:30,img:'https://images.unsplash.com/photo-1584622781867-1b3d6f2f6e3d?auto=format&fit=crop&w=800&q=80'}];
let products=JSON.parse(localStorage.getItem('bp_products')||'null')||demo,cart=JSON.parse(localStorage.getItem('bp_cart')||'[]');
const cats=['الكل','الكوزينة','لافابو','الشوفو','الضو','الغاز','الحمامات','أدوات ومستلزمات'];
const save=()=>{localStorage.setItem('bp_products',JSON.stringify(products));localStorage.setItem('bp_cart',JSON.stringify(cart))};
function store(){document.body.className='';app.innerHTML=`<div class="top">🚚 توصيل سريع لجميع المدن المغربية • خدمة الزبناء</div><header><div class="head"><button onclick="location.hash='admin'">👤</button><div class="logo">⌂ <b>Bayti<span>Pro</span></b><small>كل ما تحتاجه لتجهيز دارك</small></div><button onclick="cartBox()">🛒 <i>${cart.length}</i></button></div><div class="search"><input id="q" placeholder="إبحث عن منتج، صنف أو ماركة..." oninput="renderProducts()"> 🔍</div></header><nav>${cats.map(c=>`<button onclick="setCat('${c}')">${c}</button>`).join('')}</nav><main><section class="hero"><div><b>عروض استثنائية</b><h1>على تجهيزات <strong>الكوزينة</strong></h1><p>جودة عالية • ماركات معروفة • أسعار تنافسية</p><em>خصومات تصل إلى<br><strong>-50%</strong></em><button onclick="document.querySelector('#offers').scrollIntoView()">تسوق الآن</button></div></section><section><h2>🔥 عروض اليوم</h2><div id="offers" class="products"></div></section><section class="promos"><article>🚿 <b>تجهيزات الحمامات</b><small>راحة وأناقة في دارك</small></article><article>💡 <b>إضاءة عصرية</b><small>لجمال بيتك</small></article><article>🔥 <b>غاز آمن وموثوق</b><small>لجميع استعمالاتك</small></article></section></main><footer>🚚 توصيل سريع　 🔒 دفع آمن　 🎧 خدمة الزبناء　 🛡️ ضمان الجودة</footer><div class="bottom">⌂ الرئيسية　 ▦ التصنيفات　 🔍 البحث　 🛒 السلة　 👤 حسابي</div>`;renderProducts()}
let active='الكل';function setCat(c){active=c;renderProducts()}function renderProducts(){let q=(document.getElementById('q')?.value||'').toLowerCase();let a=products.filter(p=>(active==='الكل'||p.cat===active)&&p.name.toLowerCase().includes(q));document.getElementById('offers').innerHTML=a.map(p=>`<article class="card"><span>-${p.disc}%</span><img src="${p.img}"><h3>${p.name}</h3><del>${p.old} DH</del><strong>${p.price} DH</strong><button onclick="add(${p.id})">🛒 أضف إلى السلة</button></article>`).join('')}
function add(id){cart.push(products.find(p=>p.id===id));save();store();alert('تمت إضافة المنتج للسلة ✅')}
function cartBox(){if(!cart.length)return alert('السلة فارغة');let total=cart.reduce((s,p)=>s+p.price,0);let name=prompt('الاسم الكامل');if(!name)return;let phone=prompt('رقم الهاتف');if(!phone)return;let city=prompt('المدينة');if(!city)return;let orders=JSON.parse(localStorage.getItem('bp_orders')||'[]');orders.unshift({id:Date.now(),name,phone,city,items:cart,total,status:'new'});localStorage.setItem('bp_orders',JSON.stringify(orders));cart=[];save();alert('تم إرسال الطلب بنجاح ✅');store()}
function admin(){document.body.className='admin';app.innerHTML=`<aside><div class="logo">⌂ <b>Bayti<span>Pro</span></b></div><button onclick="adminHome()">📊 الرئيسية</button><button onclick="adminProducts()">📦 المنتجات</button><button onclick="adminOrders()">🛒 الطلبات</button><button onclick="location.hash=''">🏠 المتجر</button></aside><main class="panel"><div id="adminContent"></div></main>`;adminHome()}
function adminHome(){let o=JSON.parse(localStorage.getItem('bp_orders')||'[]');adminContent.innerHTML=`<h1>لوحة التحكم</h1><div class="stats"><div>📦<b>${products.length}</b><small>المنتجات</small></div><div>🛒<b>${o.length}</b><small>الطلبات</small></div><div>🔥<b>${o.filter(x=>x.status==='new').length}</b><small>طلبات جديدة</small></div><div>💰<b>${o.reduce((s,x)=>s+x.total,0)} DH</b><small>المبيعات</small></div></div>`}
function adminProducts(){adminContent.innerHTML=`<div class="bar"><h1>المنتجات</h1><button onclick="edit()">＋ إضافة منتج</button></div><div class="adminlist">${products.map(p=>`<div><img src="${p.img}"><b>${p.name}</b><strong>${p.price} DH</strong><button onclick="edit(${p.id})">✏️</button><button onclick="del(${p.id})">🗑️</button></div>`).join('')}</div>`}
function edit(id){let p=id?products.find(x=>x.id===id):{id:Date.now(),name:'',cat:'الكوزينة',price:0,old:0,disc:0,img:''};let n=prompt('اسم المنتج',p.name);if(n===null)return;p.name=n;p.price=Number(prompt('الثمن',p.price)||0);p.old=Number(prompt('الثمن القديم',p.old)||0);p.disc=Number(prompt('التخفيض %',p.disc)||0);p.cat=prompt('التصنيف',p.cat)||p.cat;p.img=prompt('رابط صورة المنتج',p.img)||p.img;if(!id)products.unshift(p);save();adminProducts()}
function del(id){if(confirm('حذف المنتج؟')){products=products.filter(p=>p.id!==id);save();adminProducts()}}
function adminOrders(){let o=JSON.parse(localStorage.getItem('bp_orders')||'[]');adminContent.innerHTML=`<h1>الطلبات</h1>${o.map(x=>`<article class="order"><b>#${String(x.id).slice(-6)}</b><h3>${x.name}</h3><p>📞 ${x.phone}　📍 ${x.city}</p><strong>${x.total} DH</strong><select onchange="status(${x.id},this.value)"><option value="new" ${x.status==='new'?'selected':''}>جديد</option><option value="confirmed">تم التأكيد</option><option value="shipping">قيد التوصيل</option><option value="delivered">تم التسليم</option><option value="cancelled">ملغى</option></select></article>`).join('')||'<p>ما كاين حتى طلب.</p>'}`}
function status(id,v){let o=JSON.parse(localStorage.getItem('bp_orders')||'[]');o=o.map(x=>x.id===id?{...x,status:v}:x);localStorage.setItem('bp_orders',JSON.stringify(o));adminOrders()}
window.onhashchange=()=>location.hash==='#admin'?admin():store();location.hash==='#admin'?admin():store();
